# ใช้ image ของ Node.js
FROM node:16

# กำหนด working directory
WORKDIR /app

# คัดลอกไฟล์ทั้งหมดจากเครื่องไปยัง container
COPY . /app

# ติดตั้ง dependencies
RUN npm install

# เปิดพอร์ต 3000
EXPOSE 3000

# สั่งให้รันแอป
CMD ["npm", "start"]
